### ISSUE TITLE
How do i configure dead letter exchange from JMS API 

### ISSUE THREAD

**Issue by gihanmaduranga** [rabbitmq/rabbitmq-jms-client#108]
My requirement is to part of the job submission to the queue I want to create a dead letter exchange for that particular routing key. This can be done via overriding parameters using [Spring AMQP library](https://spring.io/projects/spring-amqp). 

```
QueueBuilder.durable(Constants.INCOMING_QUEUE_NAME)
                .withArgument("x-dead-letter-exchange", "")
                .withArgument("x-dead-letter-routing-key", Constants.DEAD_LETTER_QUEUE_NAME)
                .build();
```

Following is the JMS client code snippet.
```
RMQConnectionFactory connectionFactory = new RMQConnectionFactory();
	        connectionFactory.setUsername(userName);
	        connectionFactory.setPassword(password);
	        connectionFactory.setHost(hostName);
	      
	        RMQDestination jmsDestination = new RMQDestination();
	        jmsDestination.setAmqp(false);
	        jmsDestination.setQueue(true);
	        jmsDestination.setAmqpExchangeName(exchanger.name());
	        jmsDestination.setAmqpRoutingKey(queueName);
	        jmsDestination.setDestinationName(queueName);
	        jmsDestination.setAmqpQueueName(queueName);
	        
			try (Connection connection = connectionFactory.createConnection();Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE)) {
				
				connection.start();
				MessageProducer producer = session.createProducer(jmsDestination);
				TextMessage msg = session.createTextMessage(JsonWrapper.toJsonUsingJackson(message));
				msg.setJMSType("TextMessage");
producer.send(msg );
}
```
So is there any way to achive the same thing in RabbitMQ JMS client API?

Thanks.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
From [DLX documentation guide](https://www.rabbitmq.com/dlx.html):

```
Configuration using policies is recommended as it allows for DLX reconfiguration
that does not involve application redeployment.
```

another upside is that it works the same regardless of what client it used. JMS API is largely unaware of vendor-specific features such as DLX.
