### ISSUE TITLE
Queue isn't declared/bound if destination is an amqp destination

### ISSUE THREAD

**Issue by SethPyle376** [rabbitmq/rabbitmq-jms-client#122]
https://github.com/rabbitmq/rabbitmq-jms-client/blob/9647aee859d4c9e852ed476c6818da8e87e1b97f/src/main/java/com/rabbitmq/jms/client/RMQSession.java#L682-L690

When creating a producer with an amqp destination this conditional prevents declareRMQQueue from being called. I think that making sure the queue is declared and bound correctly to the exchange would be the desired behavior like JMS destinations. I'd be happy to submit a change to this, just wanted to make sure I understood this fully.

**Comment by michaelklishin** [comment]
We will have to wait for @acogoluegnes to come back next week as I don't know the answer. The method has been mostly unchanged for seven years, with the exception of https://github.com/rabbitmq/rabbitmq-jms-client/commit/1eac647bba403fd96e0f0fd6c6d298c564171fb6.

**Comment by acogoluegnes** [comment]
I'm not the original author of this code and the semantics of an "AMQP destination" are actually not fully defined somewhere, but looking at the code, I'd say this is the normal behavior.

An AMQP destination is supposed to be backed up by already existing AMQP resources (exchange, binding, queue), this is what the existing code and a [comment](https://github.com/rabbitmq/rabbitmq-jms-client/blob/3200e3455f2233071e4dd9c493e3395db950f124/src/main/java/com/rabbitmq/jms/admin/RMQDestination.java#L107) suggest. So basically when an application refers to an AMQP destination, everything is supposed to be set beforehand.

This actually makes sense when you consider there's no enough information to create the AMQP destination (e.g. which type of exchange), only what is necessary to publish to the queue and consume from it is in `RMQDestination`.

The JMS client creates its own AMQP resources for pure JMS destinations because it settled down on a JMS-to-AMQP mapping (which is an implementation detail), but it's not the case for AMQP destinations.

So unless there's a good reason, I would not change this behavior or even add an opt-in to change it (the JMS client has already a bunch of these).

**Comment by SethPyle376** [comment]
That makes a lot of sense, thanks for the great explanation.
