### ISSUE TITLE
Is RabbitMQ JMS Topic Exchange Plugin prerequisite or optional?

### ISSUE THREAD

**Issue by samdai** [rabbitmq/rabbitmq-jms-client#20]
If Rabbitmq server hasn't enabled RabbitMQ JMS Topic Exchange plugin?  can this rabbitmq-jms-client still work? what features can't be supported if RabbitMQ JMS Topic Exchange plugin is not enabled?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.Знаешь

**Comment by michaelklishin** [comment]
Topic selectors won't work without the plugin. Use this client without its respective server plugin at your own risk.
