### ISSUE TITLE
Message JMS properties are largely ignored

### ISSUE THREAD

**Issue by damonsutherland** [rabbitmq/rabbitmq-jms-client#25]
I am using the 1.6 client and I noticed that setting any message attribute except JMSCorrelationId and JMSType are ignored in favor of the message producer settings.  My expectation, and experience with other JMS clients (e.g. ActiveMQ), is that when I set Message properties they take precedence, unless a producer.send overload was used (and only for the properties represented in the overload).

Is there a reason I am overlooking that this doesn't occur with the RMQ JMS client, or is this a defect?

Also, there is a comment in the RMQMessage.copyAttributes  that says JMSReplyTo is ignored completely.  Same question, is there a reason or is this a defect?

Thanks for looking into this.

**Comment by damonsutherland** [comment]
After looking at the spec in more detail, it is a bit misleading.  I think either interpretation could be made, but if you always use the Producer defaults for DeliveryMode, Priority and Expiration, you eliminate the possibility of overriding them on a message by message basis.  

I'm still confused by the JMSReplyTo being ignored, but I would understand if you chose not to address the other properties.

Thanks again.

**Comment by michaelklishin** [comment]
Hi, our team would appreciate if you used the mailing list, rabbitmq-users, for questions in the future. We do not use GitHub issues for questions.

The original author of this client is no longer on our team and https://github.com/rabbitmq/rabbitmq-jms-client/commit/afa2d977bcc55b904850eccc966977009670af28 does not provide a justification or a clear link to an issue of some kind that I could research. However, the intent seems to be to
move message property mapping from `RMQMessage`, which is very generic, to `RMQMessageProducer` and specific message types.

As for `ReplyTo`, at of early 2014, there was no good way to map it because [request/reply implementation](https://www.rabbitmq.com/tutorials/tutorial-six-java.html) had to use. Later the same year [Direct reply-to](http://www.rabbitmq.com/direct-reply-to.html) was introduced, which makes the mapping less opinionated. I'm not entirely sure it's a good fit but it makes sense to investigate the support for that field. It has to be a separate, non-question issue.

**Comment by damonsutherland** [comment]
Thanks.  I apologize for not using the mailing list.  I'll be sure to do so in the future.

The bug I was trying to communicate was that JMSReplyTo is null in the consumer when set in a message sent by a separate MessageProducer.  I'll restate the issue in the mailing list.  

Thank you for your answer though.  I really do appreciate it and again, sorry for using the wrong forum.
