### ISSUE TITLE
Setting multiple hosts to RMQConnectionFactory

### ISSUE THREAD

**Issue by tutnhamon** [rabbitmq/rabbitmq-jms-client#50]
It would be useful if there was a way to provide multiple connection endpoints (host:port pairs, for example) the same way it is possible in the regular RabbitMQ Java client.

**Comment by michaelklishin** [comment]
Please use rabbitmq-users for questions.

The API assumes a single URI. Supporting multiple URIs should be possible but RabbitMQ Java client, while it supports multiple hosts, only supports a single URI. We'd need to investigate what would be possible and easy enough to use and understand.

This issue is specific enough to keep open. I will update the description if you don't mind.

@acogoluegnes WDYT?

**Comment by acogoluegnes** [comment]
This makes sense to me. I think adding an `AddressResolver` property and an array of `Address` property should do the trick. Both would delegate to the appropriate `ConnectionFactory` methods.
